### ISSUE TITLE
Stop using map_dict* and just use maps

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_typer#16]
## `rebar3_typer` version
[0.0.1](https://github.com/AdRoll/rebar3_typer/releases/tag/0.0.1)

## `OS` version
All

## Description
* **Motivation**
`rebar3_mini_typer` uses `map_dict*` functions to manipulate its internal dictionary, mainly because it inherited that code from `typer`, which was written before the existence of maps.

* **Proposal**
Two steps:
1. Switch the implementation of `map_dict` to maps instead of `dict` and verify that it still works.
2. Remove those functions and use map-pattern-matching directly in the code instead.

## Current behavior
`rebar3_mini_typer` uses `map_dict_*` functions.

## Expected behavior
`rebar3_mini_typer` to use maps directly.

## Config
None.

**Comment by maco** [comment]
I replaced dict with map in the record and in the wrapper functions, but I am confused on part 2. Is that meaning get rid of the `map_lookup` function? (And what about record versus map?)

**Comment by elbrujohalcon** [comment]
I'll reply in #30
